# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Perobscurus
email: christophercampbell at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some obscure stuff I come across while walking around
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://christophercampbell.github.io" # the base hostname & protocol for your site
twitter_username: fuquier
github_username:  christophercampbell

# Build settings
markdown: kramdown

repository: christophercampbell/christophercampbell.github.io

excerpt_separator: <!--more-->

# Url style
permalink: /:title

# Pagination
paginate: 5
paginate_path: "/blog/page:num"

