# Site settings
title: Perobscurus

plugins: [jekyll-paginate]

# the base hostname & protocol for the site
url: "http://christophercampbell.github.io" 

# the subpath of the site, e.g. /blog
baseurl: "" 

repository: christophercampbell/christophercampbell.github.io

email: christophercampbell at gmail.com

description: "perobscurus, /pe.ropˈskuː.rus/, [pɛ.rɔpˈskuː.rʊs] : obscure or vague"

github_username:  christophercampbell

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

# Url style
permalink: /:title

# Pagination
paginate: 5

paginate_path: "/blog/page:num"

