#!/bin/bash

if [ "$#" -ne 1 ] ; then
  echo "Usage: $0 <title>" >&2
  exit 1
fi

EDITOR=/opt/sublime

title=`echo "$1" | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]'`
fileName="_posts/`date +%Y-%m-%d-$title.md`"

touch $fileName

cat > $fileName <<DELIM
---
layout: post
title: "$1"
date:  `date "+%Y-%m-%d %H:%M:%S"`
categories: 
---

![Image](/assets/image.png)

DELIM

$EDITOR $fileName
