#!/bin/bash

if [ "$#" -ne 1 ] ; then
  echo "Usage: $0 <title>" >&2
  exit 1
fi

EDITOR=/opt/sublime

title=$1

titleString=`echo "$1" | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]'`

image=/images/image

# todo: _drafts would be a natural place to put it also, then: jekyll serve --drafts for preview
fileName="_posts/`date +%Y-%m-%d-$titleString.md`"

touch $fileName

cat > $fileName <<DELIM
---
layout: post
title: "$title"
date:  `date "+%Y-%m-%d %H:%M:%S"`
tags: 
---

![$1]($image)

<!--more-->

DELIM

$EDITOR $fileName
